{% set data = load_setup_py_data() %}

package:
  name: streamvis
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - streamvis = streamvis.cli:main

requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numba
    - bokeh =2.1
    - jungfrau_utils =3.7
    - pyzmq
    - pillow >=4.3
    - colorcet
    - bottleneck

test:
  source_files:
    - tests
  requires:
    - pytest

about:
  home: https://github.com/paulscherrerinstitute/streamvis
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
